# -*- coding: utf-8 -*-
"""Iris-Visualization.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1smiWkipbgpK0ty7Ka3l-5ClWO0yEc-kO
"""

from google.colab import files
uploaded_file = files.upload()

import pandas as pd
import seaborn as sns

import io

data = pd.read_csv(io.BytesIO(uploaded_file['Iris.csv']))
data.info()

data.isnull().sum() # checking for null values in any of the columns

data = data.drop(["Id"], axis=1) # dropping the 'Id' column, as it is unnecessary
data.info()

data.Species.replace({"Iris-setosa":"setosa", "Iris-versicolor":"versicolor", "Iris-virginica":"virginica"},inplace=True)

data.describe().T

sns.heatmap(data.corr(),annot=True)

sns.pairplot(data, hue="Species")

